#!/usr/bin/env ruby

# script/update: Update gem to run for its current checkout.

require 'fileutils'
include FileUtils

APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  puts '==> Installing dependencies'
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')
end
